const Sequelize= require('sequelize');
const sequelize = require('../utils/database');

var User = sequelize.define('user',{
    uid:{
        type:Sequelize.STRING(120),
        primaryKey:true,
        allowNull:false,
        unique:true
    },
    fullName:{
        type:Sequelize.STRING(120),
        defaultValue:"",
        allowNull:true
    },
    emailID:{
        type:Sequelize.STRING(120),
        defaultValue:"",
        allowNull:true
    },
    password:{
        type:Sequelize.STRING(120),
        defaultValue:"",
        allowNull:false
    },
    otp:{
        type:Sequelize.STRING(120),
        defaultValue:"",
        allowNull:false
    },
    isActive:{
        type: Sequelize.BOOLEAN,
        defaultValue: true
    },
    emailverifylink:{
        type:Sequelize.STRING(120),
        defaultValue:"",
        allowNull:true,
    },
    isEmailverified:{
        type:Sequelize.BOOLEAN,
        defaultValue:false,
    },
    userRole:{
        type:Sequelize.STRING(100),
        allowNull:false,
        defaultValue:'user'
    },
    profileImageLink:{
        type:Sequelize.STRING(200),
        allowNull:true,
    },
    headerImageLink:{
        type:Sequelize.STRING(200),
        allowNull:true,
    },
    firstName:{
        type:Sequelize.STRING(200),
        allowNull:true,
    },
    lastName:{
        type:Sequelize.STRING(200),
        allowNull:true,
    },
    phone:{
        type:Sequelize.STRING(500),
        allowNull:true,
    },
    street:{
        type:Sequelize.STRING(500),
        allowNull:true,
    },
    city:{
        type:Sequelize.STRING(500),
        allowNull:true,
    },
    state:{
        type:Sequelize.STRING(500),
        allowNull:true,
    },
    zip:{
        type:Sequelize.STRING(500),
        allowNull:true,
    },
    country:{
        type:Sequelize.STRING(500),
        allowNull:true,
    },
    isDeleteRequest:{
        type:Sequelize.BOOLEAN,
        defaultValue:false
    },
    requestDeleteDate:{
        type:Sequelize.DATE
    },
    loginAttempt:{
        type:Sequelize.INTEGER,
    },
    isBlocked:{
        type:Sequelize.BOOLEAN,
        defaultValue:false
    },
    resetToken:{
        type:Sequelize.STRING,
        defaultValue:null
    },
    tokenExpires:{
         type:Sequelize.DATE,
         defaultValue:null
    }
});

module.exports=User;